### ISSUE TITLE
Write output into a single file per deployment

### ISSUE THREAD

**Issue by hendrikmaus** [hendrikmaus/helm-templexer#36]
~Some~ We prefer to collect the rendered manifests of a chart in a single file rather than passing `--output-dir` to `helm template`.

A theoretical (and abstract) scenario might look like so (also a template for an integration test):

```shell
helm-templexer render config0.yaml config1.yaml
```

```yaml
---
# config0
release_name: prometheus
output_path: manifests
deployments:
- name: edge
- name: stage

---
# config1
release_name: grafana
output_path: manifests
deployments:
- name: edge
- name: stage
```

And the resulting directory tree should look like:

```
manifests/
  edge/
    prometheus.yaml
    grafana.yaml
  stage/
    prometheus.yaml
    grafana.yaml
```

Where every file was created by piping `stdout` of `helm template` into a file.

~Extend the configuration to allow for configuring the output behavior while keeping the current behavior as default.~
