### ISSUE TITLE
Add an option to call helm dependencies update

### ISSUE THREAD

**Issue by arnecls** [hendrikmaus/helm-templexer#46]
When rendering a chart, external dependencies might not be present.
Helm will then complain about missing charts, which can be fixed by running `helm dependencies update`.

It would be nice to have an `--update` option that you can pass to the helm-templexer render command to automatically update dependencies before rendering.

**Comment by hendrikmaus** [comment]
Hey @arnecls, this can be achieved using the "additional options" feature in the templexer. However, I see your point, because it would be enough to call the update process exactly *once* per render process, instead of multiple times, like shown in the following "workaroudns".

You can use it in three places right now:

1. globally on `helm-templexer render --additional-options="--dependency-update" templexer.yaml
`
2. also globally in the config

    ```yaml
    ---
    version: v1
    enabled: true
    chart: nginx-chart
    namespace: my-namespace
    release_name: my-app
    output_path: manifests
    additional_options:
      - "--skip-crds"
      - "--no-hooks"
      - "--dependency-update"              # <-- will add it for each deployment
    values:
      - nginx-chart/values/default.yaml
    deployments:
      # snip
    ```

3. per deployment

    ```yaml
    ---
    version: v1
    enabled: true
    chart: nginx-chart
    namespace: my-namespace
    release_name: my-app
    output_path: manifests
    additional_options:
      - "--skip-crds"
      - "--no-hooks"
    values:
      - nginx-chart/values/default.yaml
    deployments:
      - name: edge-eu-w4
        values:
          - nginx-chart/values/edge.yaml
        additional_options:
          - "--dependency-update"          # <-- would add it only for the `edge-eu-w4` deployment
      - name: next-edge-eu-w4
      # snip
    ```
